sonar.projectKey=hello-node
sonar.projectName=Hello Node
sonar.projectVersion=2.0

sonar.sources=hello-world.js
sonar.tests=hello-world.test.js

sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
